### ISSUE TITLE
[NEW Proxy]

### ISSUE THREAD

**Issue by Huanaco51438** [WhatsApp-Proxy/whatsapp-proxies-web#166]

**Comment by Huanaco51438** [comment]
Ports for all proxies:
port http/https 50100
socks5 50101

Login: tunco_514
Password: 3HDxVCC9It
Your IPs:

115.167.26.103

**Comment by GewoonJaap** [comment]
I tried connecting to the ip and chat port 50100 without any success.

**Comment by Huanaco51438** [comment]
Same here

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by GewoonJaap** [comment]
Okay.. Please only post proxies that you own/know that work. I have deleted the message for now because it contains a password..
