### ISSUE TITLE
[FEAT] unlimited Youtube through whatsapp, help for desperate parents.

### ISSUE THREAD

**Issue by xwischi4225** [WhatsApp-Proxy/whatsapp-proxies-web#169]
## Description
Problem: Parents need a way to manage children's YouTube viewing within WhatsApp, as current parental controls on devices or apps do not extend to media shared via WhatsApp messages.
## Solution
Proposed Feature: Implement a feature in the WhatsApp Proxy service that can filter and block specific URLs, such as those from YouTube, from being accessed through WhatsApp. This would allow parents to prevent their children from watching YouTube videos shared within WhatsApp chats.
## Why is this the best solution?
Alternatives Considered: Other solutions might involve more general internet filtering tools or device-level parental controls, but these do not offer the precision of blocking content accessed specifically through WhatsApp.

Advantages: This solution is targeted and precise, allowing for a balanced approach where children can still use WhatsApp for messaging but are restricted from accessing potentially distracting or inappropriate video content.

**Comment by GewoonJaap** [comment]
This is something out of scope of the whatsapp proxy. You should consider looking at tools like adguard home to block YouTube all together
