### ISSUE TITLE
Proxy WhatsApp

### ISSUE THREAD

**Issue by Lib7782** [WhatsApp-Proxy/whatsapp-proxies-web#229]
Connectez-vous à WhatsApp à l’aide du proxy suivant. https://wa.me/proxy?host=65.109.65.179&chatPort=8444&mediaPort=588&chatTLS=true

**Comment by GewoonJaap** [comment]
Hi,
Thanks for the feature request. I think this would be a great addition to the website.
Will try to implement this as soon as possible
