### ISSUE TITLE
[NEW Proxy] ghajar

### ISSUE THREAD

**Issue by alirezabalsa** [WhatsApp-Proxy/whatsapp-proxies-web#4]
## IP address
51.14.190.56:5222

## Port
443

## Country
566
<!- The country the proxy is located in -->

**Comment by GewoonJaap** [comment]
Thanks! I will add it. Have you changed the SSL_SUBJECT to something random?

![Screenshot_20230109-201948](https://user-images.githubusercontent.com/33700526/211390681-689050ec-332c-4ae0-ba77-804b6e420490.png)
Otherwise the proxy is blocked in China

**Comment by GewoonJaap** [comment]
This proxy is already added
