### ISSUE TITLE
[NEW Proxy]

### ISSUE THREAD

**Issue by capsload2** [WhatsApp-Proxy/whatsapp-proxies-web#5]
[delete]

**Comment by GewoonJaap** [comment]
https://github.com/WhatsApp/proxy

I cloned this repo, `cd` into `proxy/src`
edit `generate-certs.sh`
Replace content of `CA_SUBJECT` with something random
Replace content of `SSL_SUBJECT` with something random
Save

go to `proxy/ops`
`docker-compose up -d`
