### ISSUE TITLE
[I18N] indonesia

### ISSUE THREAD

**Issue by Agtrrzunvtz** [WhatsApp-Proxy/whatsapp-proxies-web#68]
## Screenshots or videos

<details>
<summary>Click to expand</summary>

</details>

**Comment by GewoonJaap** [comment]
@Agtrrzunvtz Feel free to open a pull request where you translated all the strings to Indonesian. You can find those files here: https://github.com/WhatsApp-Proxy/whatsapp-proxies-web/tree/main/src/lib/locale/lang
