### ISSUE TITLE
Incorrect padding in-between proxy list and 'Add your proxy here'

### ISSUE THREAD

**Issue by AnonymousWP** [WhatsApp-Proxy/whatsapp-proxies-web#9]
As you can see on https://whatsapp-proxy.com/, there's an overlap between the proxy list and the string 'Add your proxy here':

![image](https://user-images.githubusercontent.com/50231698/212102710-4d9c08e9-f7f2-4cda-8d68-240546c97c81.png)

**Comment by GewoonJaap** [comment]
I just pushed an update which should fix this :)

**Comment by GewoonJaap** [comment]
Could you check if it is better?

**Comment by AnonymousWP** [comment]
Thanks! Yep, this is much better.
